sudo: false

language: node_js
node_js:
- '6'
os:
- linux
- osx

matrix:
  exclude:
  - os: osx
    env: IS_PULL_REQUEST=true

cache:
  yarn: true
  directories:
  - node_modules

before_script: npm install -g grunt-cli
after_success: "./travis-nightly.sh"
# only upload failed webdriver tests on testing branch while running linux
after_failure: if [ "$TRAVIS_BRANCH" = "$SAUCE_BRANCH" ] && [ "$TRAVIS_OS_NAME" = "$SAUCE_OS" ] && [ "$GH_TOKEN" ]; then grunt gh-pages:crafty-distro-regression-tests; fi

env:
  global:
  - SAUCE_BRANCH=testing
  - SAUCE_OS=linux
  - IS_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  # GitHub token
  - secure: p6SeAGd+Gohr6XeDkb5JPSQBu88UxAjljSMK0BNLJQgr8GkoA3mSJWy4uX0YjNq93VX4UMFxr0D4MlkcWZpX+cdN8K9PpxOgTq8Ml1Ljs355zbX9U/CdY99okiwzHktY4qKXBPsHLiEuCBeJ6pxs/v7m9z88mkjwDSunJG7F1oo=
  # OpenSauce credentials: for pre-relase testing
  - secure: NO+7PK5P0XLGbnvdSDBlrlnzqM/hMTy3wxxAp8ZtzEuS2ZOXn8q0KjOO/cAs1NorG1SOl8+XfFZBTR5W504GrHYLP8fNkLJOAyKMfFeTojwQ+385ShVr/NejZFejsc+xJZymIeDsEzBZqosxPOi+8k7jljDK4mzLdKMpt8flWUw=
  - secure: iGO+VCkCq/26Dqrc6+G1nX8Dk+tTqhcINuiIVhxGtMARcY+WIzcyEK/cfXRaLnvIzIxQ0xUoGGnM9xe4DQT8L+BGzo8AGnVbzxITzceWTlhsFepcbOTgqOg0ZGMxQVQ6VBh888Cdks8KsOgtTNhzd+oVgcStsyxZPCVD/7VgNTE=

addons:
  sauce_connect:
    no_ssl_bump_domains: all
